contact_links:
  - name: Join nf-core
    url: https://nf-co.re/join
    about: Please join the nf-core community here
  - name: "Slack #wgs channel"
    url: https://nfcore.slack.com/channels/wgs
    about: Discussion about the nf-core/wgs pipeline
